name: Math Operation

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - name: Perform math operation
        run: |
          echo "INPUT_X=${{ env.X }}" >> $GITHUB_ENV
          echo "INPUT_Y=${{ env.Y }}" >> $GITHUB_ENV
          python math_operation.py
        env:
          X: ${{ github.event.inputs.x }}
          Y: ${{ github.event.inputs.y }}
